### PR TITLE
Deleted bn.po and renamed bn_IN.po to bn.po  (described in issue no #327)

### PR DESCRIPTION
**Pull request by itsPronay**
please view the issue no #327

### CODE REVIEW

**Comment by itsPronay** [comment]
nope, as for 329, I translated some lines. Give me some time, I will translate the whole document.

**Comment by rafaelmardojai** [comment]
Please also remove `bn_IN` from `po/LINGUAS`.

**Comment by itsPronay** [comment]
Sorry for the mistake, Please check again and let me know

**Comment by rafaelmardojai** [comment]
Looks good, with this #329 can be closed without merging right?

**Comment by itsPronay** [comment]
yes.. if this is merged, no need to merge #329

**Pull request merged**
