### PR TITLE
Added "Artwork by" in gettext, both to src/about.py and po/blanket.pot

### PR DESCRIPTION
**Pull request by Porrumentzio**
Since now that wasn't translatable. Creating new `po` from `pot` with Poedit works well and adds that string, but I don't know how to update `po` files.

### CODE REVIEW

**Comment by Porrumentzio** [comment]
I achieved to update a current Basque `po`, but not all at once.

**Comment by rafaelmardojai** [comment]
This string is translated in the toolkit level. We don't need to translate this again.

**Comment by Porrumentzio** [comment]
So it should be translated on Gstreamer?

**Comment by rafaelmardojai** [comment]
GTK https://gitlab.gnome.org/GNOME/gtk/

**Comment by Porrumentzio** [comment]
Thanks, I'll update those translations.

**Comment by rafaelmardojai** [comment]
As a note, to update translations with potfiles changes, you should:
 ```bash
# Build
meson builddir
# Update
ninja -C builddir blanket-update-po
```

**Pull request closed without merging**
