### PR TITLE
Add info about AUR in README

### PR DESCRIPTION
**Pull request by apandada1**
There is an AUR package https://aur.archlinux.org/packages/blanket. I have tested that it works.

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
Could you move the `Other Methods of Installation` section above the `Build from source` one?

And format the section like:

```markdown
## Other Methods of Installation

### AUR
For Arch Linux and it's derivatives you can install it from [AUR](https://aur.archlinux.org/packages/blanket).
```

**Comment by rafaelmardojai** [comment]
Better:
```markdown
For Arch Linux and it's derivatives you can install the [blanket](https://aur.archlinux.org/packages/blanket) package from AUR.
```

**Comment by apandada1** [comment]
Sure, I will force push to change it.
Can we also add something like this between `AUR` and `Build from source`?
```
We are looking for volunteers to help us make native packages of Blanket for Debian, Fedora, and other major distributions. It would be great if you could help.
```

**Comment by rafaelmardojai** [comment]
>  Can we also add something like this between AUR and Build from source?

What about putting that under `Other Methods of Installation` as a quote?

```markdown
## Other Methods of Installation

> We are looking for volunteers to help us make native packages of Blanket for Debian, Fedora, and other major distributions. It would be great if you could help.
```

**Comment by apandada1** [comment]
Done

**Comment by rafaelmardojai** [comment]
Thanks!

**Comment by apandada1** [comment]
Blanket is now in official Arch repositories. The previous AUR link needs to be changed to https://archlinux.org/packages/community/any/blanket/

And there is a [new maintainer](https://github.com/City-busz).

**Pull request merged**
