### PR TITLE
Debian package and updated README

### PR DESCRIPTION
**Pull request by apandada1**
The PPA is live at https://launchpad.net/~apandada1/+archive/ubuntu/blanket. I have tested that it works. It does not work with Ubuntu 18.04 due to incompatibility with the GTK version, but it works with Ubuntu 20.04 (the latest LTS release) and later.

I have included the `debian` directory to the source for convenience. I am watching releases. When a new version is released, I will update the `debian/changelog` and send a pull request.

I will try to submit it to Debian after the next version is released.

### CODE REVIEW

**Comment by Porrumentzio** [comment]
Great work, thanks!

**Comment by rafaelmardojai** [comment]
Nice! Thanks for your work!

The `debian` dir should be in the root? Could we have a specific packaging directory? I don't know if `build-aux` works for that.

**Comment by apandada1** [comment]
The `debian` directory needs to be in the root (see [Foliate](https://github.com/johnfactotum/foliate/) for example) during building the package. I was planning to automatize the building process to provide a separate "daily builds PPA" (everyday, Lauchpad will copy source from GitHub and automatically build it if there is a change) , and for that this is required.

Otherwise, one can copy the `debian` directory from `build-aux` to `root` during building, but automatic building won't be possible (AFAIK).

The other option is to keep the `debian` directory alone in a separate branch, but that will complicate in automatic building process (but automatic building may still be possible after merging the branches in Launchpad. Having never done that, I am not 100% sure)

**Comment by rafaelmardojai** [comment]
I understand, I was asking if possible to have it more organized. I'm going to merge as it is.

**Pull request merged**
