### PR TITLE
Documentation: added CONTRIBUTING.md and doc/ directory

### PR DESCRIPTION
**Pull request by Porrumentzio**
Added:
* CONTRIBUTING.md with the sound part
* doc/ directory and Sound_documentation.md

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
Thanks!

Only there are some issues with the tables spacing.

**Comment by Porrumentzio** [comment]
Which problems?

**Comment by rafaelmardojai** [comment]
If you check in Github `Files changed` tab, the markdown tables are miss aligned. 

Probably related to mixed characters of `tabs` and `spaces`?

**Comment by Porrumentzio** [comment]
I saw in the second file! It's not relevant more than for comprehensibility. It will work well, but I'll change it to be more understandable :)

**Comment by rafaelmardojai** [comment]
I think, later we can change `Made changes` in `Sound_documentation.md ` to be a single section describing all included sounds data.

**Comment by Porrumentzio** [comment]
We could, yeah. I didn't add some values, such as the new ones after modifying, in order to not have a too big table.
What would you like to change?

**Comment by rafaelmardojai** [comment]
>  What would you like to change?

Nothing now really, just to be aware that when #50 is closed, this should become a single table of sounds data. Without distinguish between `New sounds`, `Replaced sounds` and `Modified sounds`.

**Comment by Porrumentzio** [comment]
Why that?

**Comment by rafaelmardojai** [comment]
Or am I miss understanding the propose of the tables?

**Comment by Porrumentzio** [comment]
For me is like a changelog about sounds. I would even also add those sounds that should be replaced and still aren't. 

**New**: where they came from (link) and when they were added. Modifications if somewhen it would be necessary to remake it.
**Replaced**: an inverted way to manage the sounds that must be replaced. Also to know when it was added.
**Modified**: same as Replaced, but knowing that the sound and its metadata does not change, but only the values.

That was my proposal, but it's not anything fixed, it can be changed without fear.

**Comment by rafaelmardojai** [comment]
Yeah, is very repetitive, but I think someone who wants to hear to a stream wouldn't be disappointed since is how is supposed to sound.

**Comment by rafaelmardojai** [comment]
If it's a changelog is fine! Let's keep it as it is.

**Pull request merged**
