### PR TITLE
Fitted and added sounds

### LINKED ISSUE #46: [Idea] Add new sounds
I recently discovered Blanket. I think it is a very interesting app and perhaps the sound catalog could be expanded by including things like: 
-sound of waves
-sound of birds 
-sound train 
[as in [asoftmurmur](https://asoftmurmur.com) / [noisli](https://www.noisli.com) / [ambient-mixer](https://www.ambient-mixer.com) ]

PS: Have you thought about improving the sound of Rain a little more? It usually looks more like a stream.

### PR DESCRIPTION
**Pull request by Porrumentzio**
* Fitted `Storm` [-7 dB]
* New `Rain`
* Added `Birds` and `Waves`

Partly fixes #46

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
Nice! 

You can remove prior audios, we can always use git to go back.

Could you add yourself as author in the about dialog?

**Comment by Porrumentzio** [comment]
I don't really know how to add myself in that dialog. Anyway, the sounds are not mine and I didn't propose them.

I already removed the prior folder

**Comment by rafaelmardojai** [comment]
> I don't really know how to add myself in that dialog. Anyway, the sounds are not mine and I didn't propose them.

I was thinking as a credit for the reviewing / audio editing work. But we can make that latter.

**Comment by Porrumentzio** [comment]
I'll do that later. Also I'll remove priors directory.

**Pull request merged**
